spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      database: mysql
base:
  backend:
    url: "/api/v1"
  frontend:
    url: "http://localhost:4200/"